### ISSUE TITLE
app is undefined when using a renderer

### ISSUE THREAD

**Issue by Zazck** [arantes555/electron-fetch#2]
add remote support for renderer user?
`Uncaught TypeError: Cannot read property 'isReady' of undefined`

this is how I fix it 
```es6
// ./lib/index.js

// line 1225
let electron;
// istanbul ignore else
if (process.versions['electron']) {
  electron = require('electron').remote; // this case we should use electron.remote
}
const isReady = !electron || electron.app.isReady() ? Promise.resolve() : new Promise(function (resolve$$1) {
  return electron.app.once('ready', resolve$$1);
});
```
I don't know anything about writing config for modules, so I can't contribute any code, sorry.

**Comment by tex0l** [comment]
Hi @Zazck, 
Thank you for your issue, however I'm not sure why you'd want to use `electron-fetch` in a renderer process since you have the native `window.fetch` available.

For this native `window.fetch` you should use inside of a `BrowserWindow`, you can configure manually its proxy configuration upon creation by configuring a custom `session` ([Session docs](https://electronjs.org/docs/api/session)) that you'd give as a property of the `webPreferences` property of the options of `BrowserWindow` in the main process:

```javascript
import {BrowserWindow, Session} from 'electron'
const session = Session.fromPartition('customSession')
// use session.setProxy for example 
const window = new BrowserWindow({
  // other BrowserWindow options
  webPreferences: {
    session
  }
})
```

If there is a reason I haven't thought of for using `electron-fetch` in a renderer process, can you please explain it?

Best,
tex0l.

**Comment by Zazck** [comment]
I'm too naive
I want to make cors request, this should be done in backend process not renderer.

Thanks for all your explaining

**Comment by mamacdon** [comment]
I'm having the same issue… Because of how my app is structured, most of the "smarts" are in the renderer. (Maybe this is a bad idea, but it reduces the amount of IPC needed.)

My web UI is served from localhost, and I want to fetch data from (say) google.com. My options are:

- `window.fetch`: Ajax request, only works for same-origin URLs (no good)
- `node-fetch`, `request`, others: don't use electron's "net" module

I was hoping to use `electron-fetch`, but ran into this limitation.

**Comment by arantes555** [comment]
@mamacdon You could probably just use `remote.require('electron-fetch')` in the renderer (where `remote = require('electron').remote`).

**Comment by arantes555** [comment]
@mamacdon you could also try using native `window.fetch` by :
- disabling the `webSecurity` setting of your window, since it's a local UI that you control.
- using this trick : https://github.com/electron/electron/issues/1990#issuecomment-497289776
